"""Correction comments user foreign key

Revision ID: 07d6866a8a4f
Revises: b0a9994add29
Create Date: 2024-10-06 15:21:52.585324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d6866a8a4f'
down_revision: Union[str, None] = 'b0a9994add29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
